### PR TITLE
#226 Resolves add completion statuses to pins/icons

### LINKED ISSUE #226: Add completion statuses to pins/icons

### PR DESCRIPTION
**Pull request by swashbuck**
Resolves #226 

I've changed the pin icon to a checkmark once the item has been visited.

hotgraphic-pin-visited

### CODE REVIEW

**Comment by oliverfoster** [comment]
I was thinking text completion for accessibility purposed, so that it reads similarly to the accordion and titles.

**Comment by swashbuck** [comment]
I can look into adding the accessibility text.  I believe we've already made that change in our project.

Sorry, I should have provided more background on the checkmark addition.  This was brought up during accessibility testing on our project:

## Bug Description:
In the Hotgraphic component, viewed/completed items indicate their completed state with a subtle graying of the graphic color. This information will be difficult or impossible to perceive for individuals with visual disabilities such as low vision or color blindness.

## Expected Behavior:

Provide a non-color dependent means of identifying viewed/completed hotgraphic items. We recommend a checkmark icon over each pin to indicate the completed state.

**Comment by swashbuck** [comment]
> I was thinking text completion for accessibility purposed, so that it reads similarly to the accordion and titles.

Actually, "visited" is already being added to the aria-label element.  Was this a recent change?

`<span class="aria-label">Hot Graphic item 2. Visited.</span>`

**Review by guywillis — COMMENTED** [review]
Could you remove the nesting from the selectors please

**Comment by oliverfoster** [comment]
> > I was thinking text completion for accessibility purposed, so that it reads similarly to the accordion and titles.
> 
> Actually, "visited" is already being added to the aria-label element. Was this a recent change?
> 
> `<span class="aria-label">Hot Graphic item 2. Visited.</span>`

No, I'm just not sure it works when the component is restored. It should be present in the template and on load, not just when the visited status changes.

**Comment by swashbuck** [comment]
> remove the nesting from the selectors

Done.

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by StuartNicholls** [comment]
We're going with ticks/check marks

**Pull request merged**
