### PR TITLE
V2 variable update

### PR DESCRIPTION
**Pull request by kirsty-hames**
- toolbar and nav buttons styling consistent.
- hover styles updated.
- button variables updated.
- h tag removed from template and updated in less.
- generic a tag styling removed and styled by class.

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1 but you have conflicts that need sorting out :-(

**Comment by guywillis** [comment]
+1

**Pull request merged**
