### PR TITLE
Fixes Hotgraphic when it is loaded on small devices issue.

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**
Fixes https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/117

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
I added this.remove() inside _.defer, so it will make sure that it will remove the element after it been created. Before it was applying remove before the element was added to the dom.

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
