### PR TITLE
Update to include _canCycleThroughPagination

### LINKED ISSUE #85: Hotgraphic should have a config option to allow pagination to cycle back around
at the moment some clients are complaining that they can click on the second item on a hotgraphic and use the pagination and miss the first option which then means they don't complete the component.

### PR DESCRIPTION
**Pull request by darylhedley**
- Update readme file
- Updated bower, .bower and package version bump
- Added to schema and example.json
- Also fixes bug with clicking the left popup navigation element and -1
index item being undefined
- No breaking changes

fixes #85

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by olivermartinfoster** [comment]
+1 needed in develop also.

**Comment by moloko** [comment]
+1

**Comment by darylhedley** [comment]
Was this tagged as a release?

**Comment by zenduo** [comment]
Added to https://adaptlearning.atlassian.net/browse/ABU-478 for inclusion in develop.

**Pull request merged**
