### PR TITLE
Fix: Title is required to set notify popup dialog label (fixes #294)

### LINKED ISSUE #294: Title is required to set notify popup dialog label
### Subject of the issue
As per Core issue [Notify role="dialog" requires a label](https://github.com/adaptlearning/adapt-contrib-core/issues/483). The popup uses the `title` to set the `dialog` [label](https://github.com/adaptlearning/adapt-contrib-core/blob/6657b362f59cccbb71e49b0e306227fd7c25ddce/js/views/notifyPopupView.js#L17).

### Expected behaviour
`Title` should be set to required as without this, the popup `dialog` won't be properly identified by assistive technologies.

### PR DESCRIPTION
**Pull request by kirsty-hames**
Fixes https://github.com/adaptlearning/adapt-contrib-hotgraphic/issues/294

### Fix
* Set `title` as `required`. Without a title, the popup `dialog` won't be properly identified by assistive technologies.

### CODE REVIEW

**Review by guywillis — APPROVED** [review]
👍

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by lemmyadams — APPROVED** [review]

**Comment by kirsty-hames** [comment]
> @kirsty-hames Does this need fixed in _component.schema.json_ as well?

Thanks @swashbuck. I wasn't too sure about this as there's a lot of inconsistencies between required properties across _component.schema.json_ and _properties.schema_. For example, there are 18 properties set to `"required": true` in [properties.schema](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/properties.schema), but only `_graphic.src` is set as required in [_component.schema.json_.](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/5d3c29448fd8f78c14b2d950ccae6466681e3d89/schema/component.schema.json#L186). 

Is this just an oversight? If so I'll raise a separate issue and just set `title` as `required` in this PR.

**Comment by swashbuck** [comment]
@joe-allen-89 @taylortom Any thoughts on Kirsty's question above? What are the guidelines for using "required" true vs. false?

**Comment by joe-allen-89** [comment]
@kirsty-hames @taylortom @swashbuck This looks to be an oversight, all the schemas were set up using adapt-octopus which seems to factor in whether the attribute has a default value for some reason before including it in the new schema - https://github.com/adapt-security/adapt-octopus/blob/d7c31730567ecbc01cbbb9ee6caa5ae534d95df7/lib/SchemaNode.js#L184

**Comment by joe-allen-89** [comment]
@taylortom I'd misunderstood that by setting a default forms expects a value, thinking the default could be changed to blank and potentially causing an issue. 

As there's no defualt value for title, we'll either need to add a default value or add it as required.

**Comment by taylortom** [comment]
@joe-allen-89 Ah yeah I think that's how legacy works actually, as there's no server validation.

With v1, you'll get the default from both the UI _and_ the API server, so if you remove the default value that's been populated for you in the form, it should be re-added again by the server API when the validation runs.

The required property then sits on top of everything else and returns an error if no value has been provided for that field.

**Comment by kirsty-hames** [comment]
This PR will need testing to confirm the latest schema commit [a5122c8](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/295/commits/a5122c8ee73d336c0d5edd133653de06b5ff9452). @joe-allen-89 / @taylortom, are you able to confirm please?

**Pull request merged**
