### PR TITLE
New: Add negative transform to hotgraphic pin (fixes #299)

### LINKED ISSUE #299: Hotgraphic pin is not static responsively
### Subject of the issue
The hotgraphic pin moves around in relation to the image it appears over responsively. This can lead to misaligned pins over images.

```
"_top": "45",
"_left": "47",
```

Desktop: 1200px
Screenshot 2024-03-06 at 15 51 33

Tablet: 768px
Screenshot 2024-03-06 at 15 52 00

### Your environment
* Master AT & FW

### Expected behaviour
Add a negative transform to the hotgraphic pin to moves the elements origin point to the centre instead of top left.

```
"_top": "50",
"_left": "50",
```

Desktop: 1200px
Screenshot 2024-03-06 at 15 53 59

Tablet: 768px
Screenshot 2024-03-06 at 15 54 12

Note: Course creators will likely have to amend the position of hotgraphic pins when updating their plugin as this fix will introduce an offset due to the element origin moving from top left to centre.

### PR DESCRIPTION
**Pull request by guywillis**
Fixes: #299 

### New
* Added config which, when enabled, adds a negative transform to hotgraphic pin so it remains stationary when viewing responsively

### CODE REVIEW

**Comment by oliverfoster** [comment]
Is every pin image going to need to be centered always?

**Comment by guywillis** [comment]
I've excluded pin images from the amend and instead only targeted pins. 

The proposed amend does not force pins to be centred on the hotgraphic image, I am only proposing that their transform origin is moved from top left to center.

The screenshots in the issue are only for illustration purpose to show the difference.

**Comment by oliverfoster** [comment]
> I am only proposing that their transform origin is moved from top left to center.

Yes. 

Is every pin image going to need to be centered always?

**Comment by oliverfoster** [comment]
Breaking is when you change something that requires other people to rework their stuff. 

There is a potential that many well placed pins, on many course, on many hotgraphics in any number of AAT will now change. That's a lot of work created by one simple transform.

**Comment by swashbuck** [comment]
Sort of like what Dan was saying, what if this was a new configurable option so that it doesn't break older courses?

`_transformOrigin`: top left (default) or center

Or if we want 'center' to be the default (which does make more sense), this could be an improvement that we implement once the migration scripts are ready. Older courses would be migrated to set this value to "top left".

**Comment by kirsty-hames** [comment]
This is something I've implemented in custom themes many times so would be good to fix the issue in the plugin itself. To avoid a breaking change I'd be incline to go with @swashbucks [suggestion above](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/300#issuecomment-2004420977).

**Comment by oliverfoster** [comment]
Could ya'll approve if in agreement please?

**Comment by guywillis** [comment]
@kirsty-hames Of course. 

Whilst it would be nice to have the option included by default I do understand and appreciate the impact of doing so is potentially huge.

**Review by oliverfoster — APPROVED** [review]

**Review by kirsty-hames — APPROVED** [review]

**Comment by swashbuck** [comment]
> I've excluded pin images from the amend and instead only targeted pins.

@guywillis What was the rationale for excluding pin images? Is the transform origin already centered?

**Comment by guywillis** [comment]
> > I've excluded pin images from the amend and instead only targeted pins.
> 
> @guywillis What was the rationale for excluding pin images? Is the transform origin already centered?

Nothing more than a misunderstanding between pin images and tiles. I shall correct, good spot.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
