### PR TITLE
Abu 947 - _useGraphicsAsPins

### PR DESCRIPTION
**Pull request by dancgray**
Used the following JSON in place of c-15 to test.

{
    "_id": "c-15",
    "_parentId": "b-10",
    "_classes": "",
    "_type":"component",
    "_component": "hotgraphic",
    "_layout": "full",    
    "title": "Hot graphic",
    "displayTitle": "Hot graphic",
    "body": "This is optional body text. Select the hotspots on the image to reveal the text. This component will scale down to a narrative when viewed on mobile.",
    "mobileBody": "This is optional body text that will be shown when viewed on mobile.",
    "instruction":"",
    "_useGraphicsAsPins": true, 
    "_canCycleThroughPagination": false, 
    "_graphic": {
      "src": "",
      "alt": "",
      "title": ""
    },
    "_items": [
      {
          "title": "Hotspot 1 title",
          "body": "This is display text 1.",
          "_graphic": {
              "src": "course/en/images/narrative_1.png",
              "alt": "alt text",
              "_classes": "cols-2 rows-1" 
          },
          "strapline": "strapline...",
          "_classes": "",
          "_top": 0,
          "_left": 0
      },
      {
          "title": "Hotspot 2 title",
          "body": "This is display text 2.",
          "_graphic": {
              "src": "course/en/images/narrative_2.png",
              "alt": "alt text",
              "_classes": "cols-2 rows-1"
          },
          "strapline": "strapline...",
          "_classes": "",
          "_top": 0,
          "_left": 50
      },
      {
          "title": "Hotspot 3 title",
          "body": "This is display text 3.",
          "_graphic": {
              "src": "course/en/images/narrative_1.png",
              "alt": "alt text",
              "_classes": "cols-2 rows-1" 
          },
          "strapline": "strapline...",
          "_classes": "",
          "_top": 50,
          "_left": 0
      },
      {
          "title": "Hotspot 4 title",
          "body": "This is display text 4.",
          "_graphic": {
              "src": "course/en/images/narrative_2.png",
              "alt": "alt text",
              "_classes": "cols-2 rows-1" 
          },
          "strapline": "strapline...",
          "_classes": "",
          "_top": 50,
          "_left": 50
      }
    ],
    "_pageLevelProgress": {
      "_isEnabled": false
    }
  },

### CODE REVIEW

**Comment by moloko** [comment]
```_useGraphicsAsPins``` is missing from example.json. Is it worth setting up two examples in example.json; one for a regular hot graphic, the other demonstrating the settings necessary for the ```_useGraphicsAsPins``` style?

**Comment by chucklorenz** [comment]
I like @moloko 's suggestion. The technique is different enough to warrant it. I think we'll save users some heartache, and documentation will be easier if there is an example to reference. I plan also to lobby for an example of this in the demo/sample course.

**Comment by dancgray** [comment]
Thanks @moloko. Sounds like we should add that as the minimum, would any of the diagrams that are on the forum be useful? (https://community.adaptlearning.org/mod/forum/discuss.php?d=693)

**Comment by chucklorenz** [comment]
Thinking we should leave the diagrams out of the repo. Let's rely on the README and wikis to cover this kind of usage detail.

**Comment by brian-learningpool** [comment]
Can you pull the Handlebars and LESS changes from 4522bfb3ae2f4af151eb598a6b15c86338d09654  too?

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
