### PR TITLE
Feature/abu 465

### PR DESCRIPTION
**Pull request by dancgray**
Add _canCycleThroughPagination, _useGraphicsAsPins and _hidePagination from master branch.

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
All tested apart from graphics as pins, do I need to modify the json for the graphics to make this work? I set to true and all I see is the title and body, nothing else?

**Comment by dancgray** [comment]
It allows you to set custom classes on items and pins. @brian-learningpool do you have a better example for the CSS?

**Comment by belal-almassri-spongeuk** [comment]
The class name will appear on the pin only if _useGraphicsAsPins : true!! and when I turned the user graphics as pin it didn't work for me, I confirm @zenduo comment that all I can see is title and body, I think this is missing CSS.

**Comment by dancgray** [comment]
I think you are right. Seems to be missing some layout/display CSS. I also get the same result from the master branch. I suggest removing _useGraphicsAsPins from this PR.

**Comment by Belal-Almassri** [comment]
It could be a great feature if it can be fixed, or if you allow adding a class to the pin and we can change the css for each pin to add background image.

**Comment by zenduo** [comment]
Hi Dan, drop me a message when you remove it and I'll re-test.

**Comment by dancgray** [comment]
@zenduo , finally got round to remove _useGraphicsAsPins. can you re-test please.

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
you need to pull in the changes to your branch

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
lol, oh dear

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
Hi guys, sorry I'm late to the party here, I completely missed this thread.

When _useGraphicsAsPins is set to true you can use a 4x2 grid to position using something like "rows-2 cols-2", or any combination.  This styling was there already.  I was hoping to expand the combinations available here but never actually found the time to get back to it.

**Comment by dancgray** [comment]
@brian-learningpool , apologies should have contacted you again. Basically I had problems testing the _useGraphicsAsPins functionality even with "rows-2 cols-2". Likely just my poor CSS skills. If you could provide a test package or similar we can test.

Would really like to get this functionality in.

**Comment by oliverfoster** [comment]
+3

**Pull request merged**
