### PR TITLE
Add _setCompletionOn, fixed ABU-489

### PR DESCRIPTION
**Pull request by dancgray**

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
could you also remove the automated tests? have a look at contrib-spoor: develop branch to see what needs to be taken out

**Comment by dancgray** [comment]
@moloko tests have been removed, also on narrative PR (https://github.com/adaptlearning/adapt-contrib-narrative/pull/120)

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
