### PR TITLE
fix for layout breaking when using 'graphics as pins'

### PR DESCRIPTION
**Pull request by bell87**
added width:100% which fixes the layout when using graphics as pins

### CODE REVIEW

**Comment by tomgreenfield** [comment]
This fixes one of the issues for me.

The [`position: absolute`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/less/hotgraphic.less#L162) is still causing problems on the buttons:

hotgraphic

**Comment by bell87** [comment]
hopefully the last commit fixes the offset images issue

**Comment by tomgreenfield** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
