### PR TITLE
Accessibility merge

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by dancgray** [comment]
+1

**Comment by moloko** [comment]
+1

One stylistic point - reading through this it's getting to be very string-heavy code - with a lot of those strings being repeated in the code... which can easily lead to bugs through mistyping. 

Need to start considering how best to reduce this, for example when there are more than a couple of repetitions - as there are for this.$('.hotgraphic-popup-count .current') - worth considering assigning to a local variable or class property

I'm not saying you need to address for this PR, it's just a general comment for consideration.

**Comment by oliverfoster** [comment]
@moloko agreed

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
