### PR TITLE
Fixes #95 - Adds missing styling

### LINKED ISSUE #95: Missing height on .hotgraphic-narrative, also add more specific class
This is missing a default height, which is causing some display issues on themes which don't define this.

Also, it would be good if the pin or tile mode was added to the hotgraphic-component markup.

### PR DESCRIPTION
**Pull request by brian-learningpool**
Also adds more specific 'pin' and 'tile' classes depending on whether _useGraphicsAsPins is set.

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Comment by ciaranlp** [comment]
apologies I had logged out of skype, a belated +1

**Pull request merged**
